config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('sondagem.urls'))
]

sondagem/urls.py
from django.urls import path
from . import views

app_name = 'sondagem'

urlpatterns = [
    path('<int:sessao_id>/pergunta/', views.pergunta_view, name='pergunta'),
    path('<int:pergunta_id>/votar/', views.votar_view, name='votar'),
    path('<int:pergunta_id>/resultados/', views.resultados_view, name='resultados'),
    path('obrigado/', views.obrigado_view, name='obrigado'),
    
]

sondagem/models.py
from django.db import models

class Sessao(models.Model):
    numero = models.IntegerField()

    def __str__(self):
        return f'Sessão No. {self.numero}'

class Pergunta(models.Model):
    sessao = models.ForeignKey(Sessao, on_delete=models.CASCADE)
    texto_pergunta = models.CharField(max_length=200)
    ativa = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.texto_pergunta}'

	
class Escolha(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    votos = models.IntegerField(default=0)
    texto_escolha =  models.CharField(max_length=200)

    def __str__(self):
        return f'{self.texto_escolha}'

sondagem/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import *

# imports para criar qrcode 
import qrcode
import qrcode.image.svg
from io import BytesIO

# imports para imprimir grafico
from matplotlib import pyplot as plt
import io
import urllib, base64
import matplotlib
matplotlib.use('Agg')



def pergunta_view(request, sessao_id):

    sessao=Sessao.objects.get(id=sessao_id)
    
    context = {}

    if Pergunta.objects.filter(sessao=sessao).exists():
        pergunta = Pergunta.objects.get(sessao=sessao)
        
    else:
        pergunta = Pergunta.objects.create(sessao=sessao, texto_pergunta="Gosta de votar?", ativa=True)
        escolha_sim = Escolha.objects.create(pergunta=pergunta, texto_escolha="Sim")
        escolha_nao = Escolha.objects.create(pergunta=pergunta, texto_escolha="Não")

    if request.method == 'POST':
        if pergunta.ativa:
            pergunta.ativa = False
        else:
            pergunta.ativa = True
        pergunta.save()

    context['pergunta'] = pergunta

    # https://medium.com/geekculture/how-to-generate-a-qr-code-in-django-e32179d7fdf2
    factory = qrcode.image.svg.SvgImage    
    uri = request.build_absolute_uri(reverse('sondagem:votar', kwargs={'pergunta_id':pergunta.id}))
    img = qrcode.make(uri, image_factory=factory, box_size=20)
    stream = BytesIO()
    img.save(stream)
    context["svg"] = stream.getvalue().decode()

    return render(request, 'sondagem/pergunta.html', context)

def votar_view(request, pergunta_id):

    pergunta = Pergunta.objects.get(id=pergunta_id)

    if  pergunta.ativa and request.method == 'POST':
        escolha_id = request.POST['escolha']
        escolha = Escolha.objects.get(id=escolha_id)
        escolha.votos += 1
        escolha.save()

        return HttpResponseRedirect(reverse('sondagem:obrigado'))

    if  pergunta.ativa:
        context = {'pergunta': pergunta}
        return render(request, 'sondagem/votar.html', context)
    else:
        return HttpResponseRedirect(reverse('sondagem:obrigado'))

    
def obrigado_view(request):

    return render(request, 'sondagem/obrigado.html')



def resultados_view(request, pergunta_id):

    pergunta = Pergunta.objects.get(id=pergunta_id)

    escolhas = [escolha.texto_escolha for escolha in pergunta.escolha_set.all()]
    votos = [escolha.votos for escolha in pergunta.escolha_set.all()]

    plt.bar(escolhas, votos)
    plt.ylabel("votos")
    plt.autoscale()

    fig = plt.gcf()
    plt.close()

    buf = io.BytesIO()
    fig.savefig(buf, format='png')


    buf.seek(0)
    string = base64.b64encode(buf.read())
    grafico = urllib.parse.quote(string)

    context = {'pergunta': pergunta, 'grafico':grafico}

    return render(request, 'sondagem/resultados.html', context)

sondagem/templates/sondagem/obrigado.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sondagem</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
        crossorigin="anonymous">
    <style>
        body {
            height: 100vh;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>

</head>

<body>
    <h1>
        Obrigado
    </h1>

</body>

</html>

sondagem/templates/sondagem/pergunta.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sondagem</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <style>
        body {
            height: 100vh;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>

</head>

<body>
    <h1>
        {{ pergunta }}
    </h1>

    <div>
        <form action="{% url 'sondagem:pergunta' pergunta.sessao.id %}" method="POST">

            {% csrf_token %}
            {% if pergunta.ativa %}
            <input type="submit" value="Fechar sondagem">
            {% else %}
            <input type="submit" value="Abrir sondagem">
            {% endif %}
        </form>
    </div>

    {% if pergunta.ativa %}
    <div class="input-group mb-3">
        <div style="margin: auto">
            {{ svg|safe }}
        </div>
    </div>
    {% endif %}

    <h3>
        <a href="{% url 'sondagem:resultados' pergunta.id %}">Resultado</a>
    </h3>

</body>

</html>

sondagem/templates/sondagem/resultados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
    <style>
        body {
            height: 100vh;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        img {
            width: 80vw;
        }
    </style>
</head>
<body>
    <h1>{{ pergunta }}</h1>
    <!-- <div>
        {% for escolha in pergunta.escolha_set.all %}
        <h2>{{escolha}}: {{escolha.votos}}</h2>
        {% endfor %}    
    </div> -->
    <div><img src="data:image/png;base64,{{ grafico }}" alt=""></div>
</body>
</html>

sondagem/templates/sondagem/votar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
    <style>
        body {
            height: 100vh;

            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <h1>{{ pergunta }}</h1>
    <form action="{% url 'sondagem:votar' pergunta.id %}" method="POST">

        {% csrf_token %}

        {% for escolha in pergunta.escolha_set.all %}
        <p>
            <label>
                <input type='radio' name='escolha' value='{{escolha.id}}'>
                {{ escolha }}
            </label>
        </p>
        {% endfor %}    

        <input type="submit" value="Votar">
    </form>
</body>
</html>